steps:
- name: gcr.io/myfirstproject-304920/npm-test
  dir: "web/sample"
  entrypoint: bash
  args:
  - 'c'
  - | -
    npm install -g @vue/cli && npm run build
- name: "gcr.io/cloud-builders/gcloud"
  dir: "web/sample"
  args: ["app", "deploy"]